### PR TITLE
Test DMD 2.080.0 and LDC 1.9.0.

### PR DESCRIPTION
**Pull request by s-ludwig**

### CODE REVIEW

**Comment by s-ludwig** [comment]
@wilzbach Do you know by chance if something has changed in the installer script? Old compiler versions fail to download ever since around the time I've opened this pull request:
```
$ source "$(CURL_USER_AGENT="$CURL_USER_AGENT" bash install.sh dmd-2.068.2 --activate)"
curl: (22) The requested URL returned error: 404 Not Found
curl: (22) The requested URL returned error: 404 Not Found
curl: (22) The requested URL returned error: 404 Not Found
curl: (22) The requested URL returned error: 404 Not Found
curl: (22) The requested URL returned error: 404 Not Found
```

**Comment by wilzbach** [comment]
> @wilzbach Do you know by chance if something has changed in the installer script? 

Yep, I do. 
It's because LATEST at code.dlang.org is pointing to 1.9.0, but no binary being there: http://code.dlang.org/download

I have made a PR to the installer script a few months ago that adds the GitHub binaries as a mirror, but sadly that one hasn't been deployed yet (and I seem to lack the permissions to do so).

**Comment by wilzbach** [comment]
See also: https://github.com/travis-ci/travis-ci/issues/9613

**Comment by s-ludwig** [comment]
Just for reference, I've also uploaded the missing binaries and will use this occasion to fix my CI setup, so that the retirement process can happen in a controlled way (e.g. also adjusting the GDC scripts that depend on it).

**Pull request merged**
