### PR TITLE
Fix a few deprecation warnings

### PR DESCRIPTION
**Pull request by wilzbach**
There's still a lot more going on. It might be worthwhile to compile all tests and examples with `-de`?

### CODE REVIEW

**Comment by wilzbach** [comment]
@s-ludwig this is passing on Travis - good to go on?

**Comment by s-ludwig** [comment]
Sorry, missed this one. Can you do a rebase?

**Comment by wilzbach** [comment]
Rebased.

**Comment by wilzbach** [comment]
Yeah - see also: https://github.com/vibe-d/vibe.d/pull/2130#issuecomment-377855683

**Pull request merged**
