### PR TITLE
openssl: Fixup long -> c_long bindings for SSL_CTX_set_options

### PR DESCRIPTION
**Pull request by Geod24**
The most common issue with C bindings strikes again.

Deimos definition: https://github.com/D-Programming-Deimos/openssl/blob/v3.0.1/source/deimos/openssl/ssl.d#L1984

### CODE REVIEW

**Comment by Geod24** [comment]
Hold on, the argument changed from `c_long` to `uint64_t` between 1.1.1 and 3.0

**Comment by Geod24** [comment]
Worked out this madness, should be G2G :crossed_fingers:

**Comment by Geod24** [comment]
@ljmf00: Can you give this a review ?

**Review by ljmf00 — APPROVED** [review]
Seems good

**Pull request merged**
