### PR TITLE
Add RestInterfaceClient.requestBodyFilter property.

### PR DESCRIPTION
**Pull request by s-ludwig**
This can be used to modify outgoing request headers based on the content of the request body.

### CODE REVIEW

**Comment by s-ludwig** [comment]
@Extrawurst Didn't really find the time to think about an optimal solution, so I just went with an `InputStream`.

**Comment by Extrawurst** [comment]
@s-ludwig That is still awesome! Thanks! How about tagging a beta after this is merged? :)

**Comment by s-ludwig** [comment]
Will do, I'll just make it an alpha for now.

**Comment by s-ludwig** [comment]
0.8.4-alpha.1 is now available.

**Pull request merged**
