### PR TITLE
Minor adjustment

### PR DESCRIPTION
**Pull request by Beyarz**
The type attribute is only useful when it's not javascript

### CODE REVIEW

**Comment by s-ludwig** [comment]
I'm not entirely sure how to go about this. It *is* technically required for HTML 3.x/4.x, but I have no idea how many people still declare their HTML documents like that these days (and additionally using this filter). Unfortunately it is not possible to know which version is used from within the filter.

**Comment by Beyarz** [comment]
> I'm not entirely sure how to go about this. It _is_ technically required for HTML 3.x/4.x, but I have no idea how many people still declare their HTML documents like that these days (and additionally using this filter). Unfortunately it is not possible to know which version is used from within the filter.

Should we just leave it as it is?

**Comment by Beyarz** [comment]
While I am at it, the type attribute is optional too

**Comment by Beyarz** [comment]
Of course if you want to support the older browsers then I can close my PR.

**Comment by s-ludwig** [comment]
Okay, I just tested it and indeed it doesn't matter in practice whether the attribute is there or not for older HTML doctypes on any of the current browser engines. So let's just go ahead with this.

**Comment by Beyarz** [comment]
Sweet!

**Pull request merged**
