### PR TITLE
HTTP request reusing TCP connection leads to wrong response being processed

### PR DESCRIPTION
**Pull request by ferencdg**
fixes: #2506

### CODE REVIEW

**Comment by Geod24** [comment]
Can you try to make the commit title a bit more descriptive ? "fixing major bug" isn't wrong, but it doesn't tell much to the reader, either :)
Additionally, is that something we could have a test for ?

**Comment by ferencdg** [comment]
> Can you try to make the commit title a bit more descriptive ? "fixing major bug" isn't wrong, but it doesn't tell much to the reader, either :)
> Additionally, is that something we could have a test for ?

I can probably write a test code to reproduce it, but it will start up a rest server, so not sure if it is a good idea to make it a unit test.

**Comment by ferencdg** [comment]
code to reproduce:

```D
	setLogLevel(LogLevel.info);
	auto settings = new HTTPServerSettings;
	settings.port = 5000;
	settings.bindAddresses = ["127.0.0.1"];
	auto router = new URLRouter;
	router.registerRestInterface(new Service);
	auto server_addr = listenHTTP(settings, router);

	runTask({
		scope (exit) exitEventLoop();
		auto settings = new RestInterfaceSettings();
		settings.httpClientSettings = new HTTPClientSettings();
		settings.httpClientSettings.readTimeout = 1.seconds;
		settings.baseURL = URL("http://127.0.0.1:5000/");
		auto service_client = new RestInterfaceClient!IService(settings);
		try {service_client.getTest(2000);} catch (Exception e) {}
		sleep(1200.msecs);
		auto result = service_client.getTest2(500);
		writeln("result:", result);
		assert(result.i == 500);
	});

	runApplication();
```

**Comment by PetarKirov** [comment]
Thanks for investigating and fixing this issue guys! That would surely save a lot of time for next one who bumps into this issue! 

> I can probably write a test code to reproduce it, but it will start up a rest server, so not sure if it is a good idea to make it a unit test.

@ferencdg in that case this folder seems like a good fit:
https://github.com/vibe-d/vibe.d/tree/master/tests

**Review by Geod24 — APPROVED** [review]

**Pull request merged**
