### PR TITLE
Avoid using closures in REST router

### PR DESCRIPTION
**Pull request by omerfirmak**
This came up while trying to add explicit dtors to one of our API arguments.
Removing trusted dgs didn't cause any problems, for our application at least.

### CODE REVIEW

**Comment by Geod24** [comment]
Both allocate ? They really should not.

**Comment by omerfirmak** [comment]
> Both allocate ? They really should not.

Seems like only the first one does. Will update.

**Comment by omerfirmak** [comment]
CI is not happy at all.

**Comment by Geod24** [comment]
Looks like some example are using the (long deprecated) `@system` API methods and the trusted lambda worked around that.

**Comment by omerfirmak** [comment]
> Looks like some example are using the (long deprecated) `@system` API methods and the trusted lambda worked around that.

I think it is a good time to end the deprecation period, what do you think?

**Comment by Geod24** [comment]
Yes

**Comment by omerfirmak** [comment]
Updated

**Comment by omerfirmak** [comment]
Updated again, turns out I missed a bunch of non-safe API.

**Pull request closed without merging**
