### PR TITLE
Fix leak when a connection is closed by the server

### LINKED ISSUE #1321: HTTP client leaks memory.
Configuration: CentOS 7 x86_64, vibe.d-0.7.26, libevent driver

There is something wrong in HTTP client error handling.
Client code:
```d
import vibe.d;

shared static this() {
	runTask({
		while(true) {
			try {
				requestHTTP("http://127.0.0.1:8080", (scope req) {
				}, (scope res) {
					res.dropBody();
				});
			} catch(Exception e) {

			}
			sleep(1.msecs);
		}
	});
}
```
If to run this code without a HTTP server, the client starts to leak memory very fast.

But if to run a simple HTTP server:
```d
import vibe.d;

shared static this()
{
	auto settings = new HTTPServerSettings;
	settings.port = 8080;
	settings.bindAddresses = ["127.0.0.1"];

	listenHTTP(settings, (req, res) {
		res.writeBody("Hello, World!", "text/plain");
	});
}
```
The client immediately stops leaking. Stop the server and you will see leak again.
If to change server code to throwing error:
```d
listenHTTP(settings, (req, res) {
	throw new HTTPStatusException(HTTPStatus.badRequest);
});
```
the client leaks, but much more slowly then without a server. But still leaks.

### PR DESCRIPTION
**Pull request by etcimon**
The higher level doesn't implement the means to track passively closed connections, other than the actual object's destructor.

For this reason, remotely closed connections will leave objects on the heap unless we finish cleaning up in `~this`.

fixes #1321

### CODE REVIEW

**Comment by s-ludwig** [comment]
Not sure about the one in `finalize`, but it's good that the one in `~this` is now legal (missed that). But I'd remove the check for passive close in the latter, because we shouldn't leak for abandoned but alive connections either. Would also be good to output a warning to the log (now that logging doesn't allocate by default).

But regardless of this low-level fix, this also needs to be fixed in the HTTP client. I'll have a look at that later.

**Comment by etcimon** [comment]
> Not sure about the one in finalize, but it's good that the one in ~this is now legal (missed that). But I'd remove the check for passive close in the latter, because we shouldn't leak for abandoned but alive connections either. Would also be good to output a warning to the log (now that logging doesn't allocate by default).

I think destruction logic belongs in finalize on every stream, because that's the last place that gets called before the GC comes around. It should be explicitely mentioned too in the definition of streams, because too often on my fork the destructor threw and triggered an infinite loop of invalid memory operations. I still get them every now and then, never sure of where it comes from.

**Comment by vitalka200** [comment]
@etcimon / @s-ludwig ,
Is there any chance it can be merged?

**Comment by s-ludwig** [comment]
@vitalka200 Do you still use the libevent driver? It looks like it wouldn't hurt to merge this, but I'm still a little hesitant, because this is ancient code, and vibe-core is a pretty mature replacement nowadays. There is a certain risk that this breaks something in a subtle way for anyone who still relies on libevent.

BTW, I expect the libevent driver to be phased out after the release of 0.8.6, unless someone raises their voice against it.

**Comment by vitalka200** [comment]
@s-ludwig Yep. 

I found it to leak less memory than vibe-core at the time when I tested it on simple "Hello, World!" example and was slightly more performant.

I've tried vibe-core again and it looks pretty good but still uses slightly more CPU than libevent wrapper (for my use-case, mainly regex matching on kubernetes pod with 0.5 cpu and 512M ram and constant ~600req/sec ).

Thank you for such great framework!

**Pull request closed without merging**
