### PR TITLE
url router test utility

### PR DESCRIPTION
**Pull request by gedaiu**
Here is a proposal for making testing routes easier. What do you think?

### CODE REVIEW

**Comment by s-ludwig** [comment]
Looks like a really useful idea. One thing I was wondering (sorry if this is obvious form the implementation, I still have to take a closer look) is if it would be feasible to implement basically the same API, but only using directly `HTTPServerResponse`, by employing some UFCS. Instead of just `URLRouter`, it would also make sense to allow any `HTTPServerRequest(Delegate/Function/Handler)` as the target.

**Comment by gedaiu** [comment]
I'm not sure I understand... where do you expect to send a `HTTPServerRequest`? As I know a server request is represented as an object not as a `Delegate/Function/Handler`.

I will try to remove the test server class and use a `HTTPServerResponse`. I know that I am using this way of testing inside a project and for some reason I was not able to use the `HTTPServerResponse`. I will try again and post here more details :)

**Comment by gedaiu** [comment]
ping @s-ludwig

**Comment by s-ludwig** [comment]
Sorry for losing track of this. I just got reminded of it due to recent [forum thread](https://forum.rejectedsoftware.com/groups/rejectedsoftware.vibed/thread/39536/).

So since `URLRouter` itself inherits from `HTTPServerRequestHandler`, it would be a simple generalization to let `request(...)` take a `HTTPServerRequestHandler`, as well as any of the other handler types.

**Pull request closed without merging**
