### PR TITLE
Bump supported compiler version to v2.098.0 and dub to the modern age

### PR DESCRIPTION
**Pull request by Geod24**
If this works on the first try I'm going to buy a lotto ticket.
Main motivation, aside from the recent release of LDC v1.28.0, is to allow using `map` with `private` function, something not possible with v2.086 based frontend as there's a nasty visibility bug.

### CODE REVIEW

**Comment by Geod24** [comment]
@s-ludwig : Will need you here as it requires changing the branch protection.

**Comment by Geod24** [comment]
@s-ludwig : This is G2G.

**Comment by Geod24** [comment]
Ping @s-ludwig

**Review by s-ludwig — APPROVED** [review]

**Comment by s-ludwig** [comment]
Sorry for the delay, I missed the previous notifications!

**Pull request merged**
