### PR TITLE
Add cmdline_mode "virtual package" for configuring commandline mode

### PR DESCRIPTION
**Pull request by FeepingCreature**
Add cmdline_mode "virtual package" to allow configuring the VibeDisableCommandLineMode version flag with dub overrides.
This will allow vibe.d to be used with the VibeDisableCommandLineMode version flag in build environments where it's awkward to customize DFLAGS, such as a shared accountwide repo of dub builds.

### CODE REVIEW

**Comment by FeepingCreature** [comment]
ping!

**Comment by FeepingCreature** [comment]
ping...

**Comment by belka-ew** [comment]
Any feedback here?

**Comment by FeepingCreature** [comment]
ping.

**Comment by FeepingCreature** [comment]
:( ping :(

**Comment by wilzbach** [comment]
How is this any better than:

1)
```
DFLAGS="-version=VibeDisableCommandLineParsing" dub build
```

2) just adding the version directly in your `dub.sdl`?

**Comment by FeepingCreature** [comment]
`DFLAGS` does not work with `dub build --build=`

**Comment by FeepingCreature** [comment]
ping

**Comment by FeepingCreature** [comment]
p i n g
i
n
g

**Comment by FeepingCreature** [comment]
p̴̗͙̫͈̭͖͉̫͉͈̭͓̟̺͕͢͠ ҉̣̫͉̤͝i̵͢͏̥̘̤̬͔̘̝͔̤͓͙̘͈͈̖̱͟ ̸͏͉̱̥̩͙̫̭̝̻̭̺̬͔̼n҉̷̹͖̦̭͚̳̭͚̟͡ͅ ̶̧̘̟͔̜͍̰̠g̢҉̸͚̼͓̦͖͉̼͙̼̰̳̀ͅ ̴̟̜̼̬͓͖͔̝̩͙̞̖̩͖̥̝̯̕͟ͅ.̡̞͕͚͙̙̘̦͕͚͉̤͓̙́͘͜ ͠͏̴̨̥̹̼͔̹̦̦̗͈̲͚̘̘̗͝.̨̝̪̤̣̼͜ ̸̵̟̖͕̮͖̬̟̳͘͜.̴̷͕̳̥̥̦̖̠̼͖̖̖̥̀

**Comment by wilzbach** [comment]
> DFLAGS does not work with dub build --build=debug/release.

Then let's better fix dub instead of adding workarounds to vibe-d?
I'm sorry but this feels like the kind of hack that just solves your personal problem, but doesn't touch the actual problem at all.

Considering that Sönke hasn't responded to this either, I'm going to close this now to save you the troubles of the constant pings.
I highly encourage you to fix it at the dub level.

**Comment by FeepingCreature** [comment]
Thanks for the response at least.

**Pull request closed without merging**
