### PR TITLE
improve json range support

### PR DESCRIPTION
**Pull request by John-Colvin**
A very simple translation of `skipNumber` to the range API.

### CODE REVIEW

**Comment by UplinkCoder** [comment]
@John-Colvin please profile the performance consequences of this change. 
It seems like it'd hurt quite a bit. please profile with `-Os` as well

**Comment by s-ludwig** [comment]
One small performance improvement would be to skip incrementing `idx` for ranges that define `length` and use `takeExactly(sOrig.length - s.length)` instead. But benchmarking is a topic that I need to get back to anyway. I did a quick test at DConf this year and performance was really bad, whereas I remember pretty good numbers from the last tests.

**Comment by John-Colvin** [comment]
The major performance problem is now fixed by operating on `ubyte[]` instead of auto-decoded strings (Oh how I hate them).

In debug mode `assumeUTF` verifies utf, which is of course expensive. In release, that check doesn't happen.

**Comment by s-ludwig** [comment]
Thanks, John! The performance implication of the additional index is supposedly small enough.

The more important question IMO is anyway to see what the future of `std_data_json` is. There were some points brought up that made it difficult to continue the Phobos integration route, so it might make sense to establish it as an independent library and let it slowly replace this module.

**Pull request merged**
